### ISSUE TITLE
Is it possible to interact with the story pages?

### ISSUE THREAD

**Issue by hepiyellow** [applitools/eyes-storybook#1]
The documentation says:
>After completing the installation and defining the API key, you will be able to run Eyes.Storybook from the command line and let it take screenshots of all your stories

## My requirement
But I wish to load the story page, interact with it (using Protractor, Puppeteer or Selenium WebDriver directly),
and then call `eyes.checkWindow`.

**Comment by pfadiaz** [comment]
Hi, we just integrated applitools to our react storybook and we are wondering the same thing.  Thanks,

**Comment by amitzur** [comment]
Thanks for your feedback,

This is an understandable requirement, of which we are aware. However, this functionality is not currently on our roadmap although it is technically possible, for the following reason:

The `Eyes.Storybook` SDK is not a natural coding environment. In order to provide this functionality, users would need to specify a puppeteer script for each story with which they wish to interact.
The same functionality can be achieved by using the [Cypress SDK](https://github.com/applitools/eyes.cypress) or a future Selenium/puppeteer SDK, by navigating to the storybook URL and performing whichever action you desire.

We will add this to our backlog. Thanks for checking out `Eyes.Storybook`, your feedback is very valuable for us and we'll be happy to hear more!
